window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "on-primary": "#ffffff",
        outline: "#737686",
        "on-primary-fixed-variant": "#003ea7",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#ffd2c4",
        "on-background": "#191b23",
        "tertiary-fixed-dim": "#ffb59d",
        "on-primary-container": "#d1daff",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "on-secondary": "#ffffff",
        "primary-container": "#0555dd",
        "surface-tint": "#0053da",
        "secondary-fixed": "#d3e4fe",
        "inverse-on-surface": "#f0f0fb",
        "surface-container": "#ededf9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#832600",
        "on-surface": "#191b23",
        "on-tertiary-fixed": "#390c00",
        "on-secondary-container": "#54647a",
        "surface-container-highest": "#e1e2ed",
        tertiary: "#862700",
        "surface-container-high": "#e7e7f3",
        "on-secondary-fixed-variant": "#38485d",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-bright": "#faf8ff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbd0",
        "surface-variant": "#e1e2ed",
        primary: "#0040ab",
        "inverse-primary": "#b4c5ff",
        "surface-container-low": "#f3f3fe",
        "on-secondary-fixed": "#0b1c30",
        "inverse-surface": "#2e3039",
        "on-primary-fixed": "#00174b",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d0e1fb",
        background: "#faf8ff",
        secondary: "#505f76",
        "tertiary-container": "#af3600",
        surface: "#faf8ff",
        "surface-dim": "#d9d9e5",
        "outline-variant": "#c3c6d7",
        "error-custom": "#E24B4A"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-max-width": "1280px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "error-text": ["Inter"],
        "headline-sm": ["Manrope"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", {lineHeight: "16px", fontWeight: "500"}],
        "body-lg": ["18px", {lineHeight: "28px", fontWeight: "400"}],
        "headline-md": ["24px", {lineHeight: "32px", fontWeight: "600"}],
        "headline-lg": ["32px", {lineHeight: "40px", fontWeight: "700"}],
        "error-text": ["12px", {lineHeight: "16px", fontWeight: "400"}],
        "headline-sm": ["20px", {lineHeight: "28px", fontWeight: "600"}],
        "body-md": ["16px", {lineHeight: "24px", fontWeight: "400"}],
        "label-sm": ["12px", {lineHeight: "14px", fontWeight: "500"}],
        "body-sm": ["14px", {lineHeight: "20px", fontWeight: "400"}]
      }
    }
  }
};
