window.tailwind = window.tailwind || {};
window.tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "secondary": "#495c94",
                      "on-primary-fixed": "#00174b",
                      "on-error-container": "#93000a",
                      "primary-container": "#0555dd",
                      "tertiary-container": "#af3600",
                      "surface-tint": "#0053da",
                      "on-primary-container": "#d1daff",
                      "secondary-fixed-dim": "#b4c5ff",
                      "tertiary-fixed": "#ffdbd0",
                      "surface-variant": "#e1e2ed",
                      "inverse-on-surface": "#f0f0fb",
                      "secondary-fixed": "#dbe1ff",
                      "surface-container-highest": "#e1e2ed",
                      "error-container": "#ffdad6",
                      "outline-variant": "#c3c6d7",
                      "surface-dim": "#d9d9e5",
                      "on-tertiary-fixed": "#390c00",
                      "outline": "#737686",
                      "surface-container-lowest": "#ffffff",
                      "surface-container-low": "#f3f3fe",
                      "on-surface-variant": "#434655",
                      "error": "#ba1a1a",
                      "on-secondary": "#ffffff",
                      "tertiary-fixed-dim": "#ffb59d",
                      "on-tertiary-container": "#ffd2c4",
                      "on-secondary-fixed-variant": "#31447b",
                      "on-primary": "#ffffff",
                      "on-tertiary-fixed-variant": "#832600",
                      "on-secondary-fixed": "#00174b",
                      "on-background": "#191b23",
                      "on-error": "#ffffff",
                      "on-surface": "#191b23",
                      "primary-fixed": "#dbe1ff",
                      "background": "#faf8ff",
                      "primary-fixed-dim": "#b4c5ff",
                      "surface-container": "#ededf9",
                      "primary": "#0040ab",
                      "inverse-surface": "#2e3039",
                      "tertiary": "#862700",
                      "surface": "#faf8ff",
                      "secondary-container": "#acbffe",
                      "on-secondary-container": "#394c84",
                      "surface-container-high": "#e7e7f3",
                      "on-primary-fixed-variant": "#003ea7",
                      "inverse-primary": "#b4c5ff",
                      "surface-bright": "#faf8ff",
                      "on-tertiary": "#ffffff"
              },
              "borderRadius": {
                      "DEFAULT": "0.125rem",
                      "lg": "0.25rem",
                      "xl": "0.5rem",
                      "full": "0.75rem"
              },
              "spacing": {
                      "lg": "24px",
                      "xs": "4px",
                      "md": "16px",
                      "xl": "48px",
                      "container-max": "1200px",
                      "base": "8px",
                      "sm": "8px",
                      "gutter": "24px"
              },
              "fontFamily": {
                      "body-sm": ["Inter"],
                      "h3": ["Inter"],
                      "h1": ["Inter"],
                      "h2": ["Inter"],
                      "body-md": ["Inter"],
                      "label-caps": ["Inter"],
                      "body-lg": ["Inter"]
              },
              "fontSize": {
                      "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
                      "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
                      "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                      "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                      "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
                      "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
                      "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
              }
            },
          },
        }
