window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#832600",
        "surface-variant": "#e1e2ed",
        "on-surface-variant": "#434655",
        "on-secondary-container": "#5e6572",
        "surface-container": "#ededf9",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3039",
        primary: "#0040ab",
        "on-tertiary": "#ffffff",
        "on-surface": "#191b23",
        "error-container": "#ffdad6",
        "primary-fixed": "#dbe1ff",
        outline: "#737686",
        "on-secondary-fixed": "#151c27",
        "surface-container-low": "#f3f3fe",
        "surface-container-highest": "#e1e2ed",
        background: "#faf8ff",
        tertiary: "#862700",
        "on-primary": "#ffffff",
        "surface-dim": "#d9d9e5",
        "secondary-container": "#dce2f3",
        "primary-fixed-dim": "#b4c5ff",
        "primary-container": "#0555dd",
        "secondary-fixed": "#dce2f3",
        "on-primary-fixed": "#00174b",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb59d",
        "tertiary-container": "#af3600",
        "inverse-on-surface": "#f0f0fb",
        "surface-bright": "#faf8ff",
        secondary: "#585f6c",
        "secondary-fixed-dim": "#c0c7d6",
        "on-primary-fixed-variant": "#003ea7",
        surface: "#faf8ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "surface-tint": "#0053da",
        "on-primary-container": "#d1daff",
        "on-tertiary-container": "#ffd2c4",
        "on-background": "#191b23",
        "on-secondary-fixed-variant": "#404754",
        "surface-container-high": "#e7e7f3",
        "on-tertiary-fixed": "#390c00",
        error: "#ba1a1a",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#ffdbd0"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        lg: "24px",
        xl: "32px",
        "container-margin": "24px",
        "2xl": "48px",
        md: "16px",
        sm: "8px",
        base: "4px",
        gutter: "16px",
        xs: "4px"
      },
      fontFamily: {
        h3: ["Be Vietnam Pro"],
        display: ["Be Vietnam Pro"],
        h1: ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        h2: ["Be Vietnam Pro"],
        "label-md": ["Be Vietnam Pro"],
        caption: ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"]
      },
      fontSize: {
        h3: ["18px", {lineHeight: "1.4", fontWeight: "600"}],
        display: ["32px", {lineHeight: "1.2", letterSpacing: "0", fontWeight: "700"}],
        h1: ["24px", {lineHeight: "1.3", fontWeight: "600"}],
        "body-lg": ["16px", {lineHeight: "1.5", fontWeight: "400"}],
        h2: ["20px", {lineHeight: "1.3", fontWeight: "600"}],
        "label-md": ["14px", {lineHeight: "1.2", fontWeight: "500"}],
        caption: ["12px", {lineHeight: "1.4", fontWeight: "400"}],
        "label-sm": ["12px", {lineHeight: "1.2", fontWeight: "600"}],
        "body-md": ["14px", {lineHeight: "1.5", fontWeight: "400"}]
      }
    }
  }
};
